<a href="https://colab.research.google.com/github/Doidjin/Deep-Learning-With-Python/blob/main/Deep_Learning_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Chapter 2 of book deep learning with Python**

**=============================================================================**

In [1]:
# Handwritten digits dataset

from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


**Training Data**

In [6]:
train_images.shape

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [3]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

**Test Data**

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
# The Network Architecture

from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [11]:
# Preparing the labels

network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [12]:
# Preparing the labels

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [14]:
# Preparing the labels

from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [15]:
# Training the Network with fit method
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2573 - accuracy: 0.9251
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1043 - accuracy: 0.9700
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0683 - accuracy: 0.9800
Epoch 4/5
469/469 [==============================] - 4s 10ms/step - loss: 0.0493 - accuracy: 0.9856
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0370 - accuracy: 0.9889


In [17]:
# Performance of the model on test set

test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.0655 - accuracy: 0.9790
